opcao = 0
while opcao != 16:
    print("1 - Cadastrar Endereco")
    print("2 - Cadastrar Escola")
    print("3 - Cadastrar Ponto de Parada")
    print("4 - Cadastrar Aluno")
    print("5 - Cadastrar Motorista")
    print("6 - Cadastrar Contrato")
    print("7 - Cadastrar Fornecedor")
    print("8 - Cadastrar Veiculo")
    print("9 - Cadastrar Rota")
    print("10 - Calcular demanda total de uma rota")
    print("11 - Exibir total de rotas")
    print("12 - Exibir total de pontos de parada")
    print("13 - Exibir tipo de pessoa")
    print("14 - Exibir informações detalhadas")
    print("16 - Sair")
    opcao = int(input("Digite a opção desejada: "))

    if opcao == 1:
        print("1 - Cadastrar Endereco")
        logradouro = input("Digite o logradouro: ")
        numero = input("Digite o número: ")
        bairro = input("Digite o bairro: ")
        cidade = input("Digite a cidade: ")
        estado = input("Digite o estado: ")
        cep = input("Digite o CEP: ")
        endereco = Endereco(logradouro, numero, bairro, cidade, estado, cep)
        print("Endereço cadastrado com sucesso!")
    elif opcao == 2:
        print("2 - Cadastrar Escola")
        nome_oficial = input("Digite o nome oficial: ")
        cnpj = input("Digite o CNPJ: ")
        endereco = input("Digite o endereço: ")
        telefone = input("Digite o telefone: ")
        nome_fantasia = input("Digite o nome fantasia: ")
        num_funcionarios = input("Digite o número de funcionários: ")
        escola = Escola(nome_oficial, cnpj, endereco, telefone, nome_fantasia, num_funcionarios)
        print("Escola cadastrada com sucesso!")
    elif opcao == 3:
        print("3 - Cadastrar Ponto de Parada")
        logradouro = input("Digite o logradouro: ")
        numero = input("Digite o número: ")
        bairro = input("Digite o bairro: ")
        cidade = input("Digite a cidade: ")
        estado = input("Digite o estado: ")
        cep = input("Digite o CEP: ")
        endereco = Endereco(logradouro, numero, bairro, cidade, estado, cep)
        ponto_parada = PontoParada(endereco)
        print("Ponto de Parada cadastrado com sucesso!")
    elif opcao == 4:
        print("4 - Cadastrar Aluno")
        nome = input("Digite o nome: ")
        cpf = input("Digite o CPF: ")
        endereco = input("Digite o endereço: ")
        telefone = input("Digite o telefone: ")
        matricula = input("Digite a matrícula: ")
        aluno = Aluno(nome, cpf, endereco, telefone, matricula)
        print("Aluno cadastrado com sucesso!")
    elif opcao == 5:
        print("5 - Cadastrar Motorista")
        nome_oficial = input("Digite o nome oficial: ")
        cpf = input("Digite o CPF: ")
        data_nascimento = input("Digite a data de nascimento: ")
        num_habilitacao = input("Digite o número da habilitação: ")
        terceirizado = input("Digite se é terceirizado: ")
        num_contrato = input("Digite o número do contrato: ")
        motorista = Motorista(nome_oficial, cpf, data_nascimento, num_habilitacao, terceirizado, num_contrato)
        print("Motorista cadastrado com sucesso!")
    elif opcao == 6:
        print("6 - Cadastrar Contrato")
        data_inicio = input("Digite a data de início: ")
        data_fim = input("Digite a data de fim: ")
        valor = input("Digite o valor: ")
        contrato = Contrato(data_inicio, data_fim, valor)
        print("Contrato cadastrado com sucesso!")
    elif opcao == 7:
        print("7 - Cadastrar Fornecedor")
        nome_oficial = input("Digite o nome oficial: ")
        cnpj = input("Digite o CNPJ: ")
        endereco = input("Digite o endereço: ")
        telefone = input("Digite o telefone: ")
        nome_fantasia = input("Digite o nome fantasia: ")
        num_funcionarios = input("Digite o número de funcionários: ")
        fornecedor = Fornecedor(nome_oficial, cnpj, endereco, telefone, nome_fantasia, num_funcionarios)
        print("Fornecedor cadastrado com sucesso!")
    elif opcao == 8:
        print("8 - Cadastrar Veiculo")
        placa = input("Digite a placa: ")
        modelo = input("Digite o modelo: ")
        ano = input("Digite o ano: ")
        cor = input("Digite a cor: ")
        num_passageiros = input("Digite o número de passageiros: ")
        veiculo = Veiculo(placa, modelo, ano, cor, num_passageiros)
        print("Veículo cadastrado com sucesso!")
    elif opcao == 9:
        print("9 - Cadastrar Rota")
        nome = input("Digite o nome: ")
        num_contrato = input("Digite o número do contrato: ")
        rota = Rota(nome, num_contrato)
        print("Rota cadastrada com sucesso!")
    elif opcao == 10:
        print("10 - Calcular demanda total de uma rota")
        nome = input("Digite o nome da rota: ")
        rota = Rota(nome)
        print("Demanda total da rota: ", rota.calcularDemandaTotal())
    elif opcao == 11:
        print("11 - Exibir total de rotas")
        print("Total de rotas: ", Rota.exibirTotalRotas())
    elif opcao == 12:
        print("12 - Exibir total de pontos de parada")
        print("Total de pontos de parada: ", PontoParada.exibirTotalPontosParada())
    elif opcao == 13:
        print("13 - Exibir tipo de pessoa")
        print("1 - Pessoa Física")
        print("2 - Pessoa Jurídica")
        opcao = int(input("Digite a opção desejada: "))
        if opcao == 1:
            print("1 - Pessoa Física")
            nome_oficial = input("Digite o nome oficial: ")
            cpf = input("Digite o CPF: ")
            endereco = input("Digite o endereço: ")
            telefone = input("Digite o telefone: ")
            data_nascimento = input("Digite a data de nascimento: ")
            pessoa = PessoaFisica(nome_oficial, cpf, endereco, telefone, data_nascimento)
            print("Tipo de pessoa: ", pessoa.verificarTipo())
        elif opcao == 2:
            print("2 - Pessoa Jurídica")
            nome_oficial = input("Digite o nome oficial: ")
            cpf = input("Digite o CPF: ")
            endereco = input("Digite o endereço: ")
            telefone = input("Digite o telefone: ")
            nome_fantasia = input("Digite o nome fantasia: ")
            num_funcionarios = input("Digite o número de funcionários: ")
            pessoa = PessoaJuridica(nome_oficial, cpf, endereco, telefone, nome_fantasia, num_funcionarios)
            print("Tipo de pessoa: ", pessoa.verificarTipo())
    elif opcao == 14:
        print("14 - Exibir informações detalhadas")
        